from __future__ import annotations

import base64
import json
import os
from functools import lru_cache
from io import BytesIO
from typing import Iterable, Sequence, Tuple

import cv2
import numpy as np
from PIL import Image, ImageOps

from inference import FaceAnalysis


DEFAULT_BLUR_THRESHOLD = float(os.getenv("BLUR_THRESHOLD", "3.0"))


@lru_cache(maxsize=1)
def get_face_analysis() -> FaceAnalysis:
    return FaceAnalysis()


def decode_base64_image(image_data: str) -> Image.Image:
    payload = image_data.split(",", 1)[-1]
    binary = base64.b64decode(payload)
    image = Image.open(BytesIO(binary))
    return ImageOps.exif_transpose(image).convert("RGB")


def is_image_blurry(image: Image.Image, threshold: float | None = None) -> bool:
    active_threshold = DEFAULT_BLUR_THRESHOLD if threshold is None else threshold
    image_array = np.array(image.convert("RGB"))
    gray = cv2.cvtColor(image_array, cv2.COLOR_RGB2GRAY)
    blur_score = cv2.Laplacian(gray, cv2.CV_64F).var()
    print(f"Blur score: {blur_score:.2f} (threshold: {active_threshold})")
    return blur_score < active_threshold


def get_face_embedding(image: Image.Image) -> np.ndarray:
    width, height = image.size
    if width < 100 or height < 100:
        raise ValueError("Image too small for face recognition")

    if is_image_blurry(image):
        raise ValueError("Image is too blurry. Please hold still and ensure good lighting.")

    analysis = get_face_analysis()

    try:
        embedding = analysis.process_image(image)
    except Exception as e:
        print(f"process_image failed: {type(e).__name__}: {e}")
        raise ValueError(f"Face model error: {e}") from e

    if hasattr(embedding, "detach"):
        embedding = embedding.detach()
    if hasattr(embedding, "cpu"):
        embedding = embedding.cpu()

    embedding_array = np.asarray(embedding, dtype=np.float32).reshape(-1)
    print(f"Embedding shape: {embedding_array.shape}, size: {embedding_array.size}")

    if embedding_array.size == 0:
        raise ValueError("Could not extract a face embedding — is a face visible in the image?")

    norm = np.linalg.norm(embedding_array)
    if not np.isfinite(norm) or norm == 0:
        raise ValueError("Invalid embedding norm generated by the model.")

    return embedding_array / norm


def compare_embeddings(embedding_a: np.ndarray, embedding_b: np.ndarray) -> float:
    if embedding_a.shape != embedding_b.shape:
        min_length = min(embedding_a.size, embedding_b.size)
        embedding_a = embedding_a[:min_length]
        embedding_b = embedding_b[:min_length]
    score = float(np.dot(embedding_a, embedding_b))
    return max(min(score, 1.0), -1.0)


def average_embeddings(embeddings: Sequence[np.ndarray]) -> np.ndarray:
    if not embeddings:
        raise ValueError("At least one image is required.")
    stacked = np.vstack(embeddings)
    averaged = stacked.mean(axis=0)
    norm = np.linalg.norm(averaged)
    if norm == 0:
        raise ValueError("Unable to build a stable embedding from the provided images.")
    return averaged / norm


def embeddings_to_json(embedding: np.ndarray) -> str:
    return json.dumps(embedding.astype(float).tolist())


def embedding_from_json(payload: str) -> np.ndarray:
    return np.asarray(json.loads(payload), dtype=np.float32)


def best_match(candidate: np.ndarray, employees: Iterable[Tuple[str, np.ndarray]]) -> Tuple[str | None, float]:
    # Convenience wrapper that returns the highest-scoring match
    matches = top_k_matches(candidate, employees, k=1)
    if not matches:
        return None, -1.0
    return matches[0]


def top_k_matches(candidate: np.ndarray, employees: Iterable[Tuple[str, np.ndarray]], k: int = 3) -> list[Tuple[str, float]]:
    """Return the top-k matches sorted by similarity (descending).

    Each entry is a tuple `(employee_id, similarity)` where similarity is in [-1, 1].
    """
    results: list[Tuple[str, float]] = []
    for employee_id, stored_embedding in employees:
        similarity = compare_embeddings(candidate, stored_embedding)
        results.append((employee_id, similarity))
    results.sort(key=lambda x: x[1], reverse=True)
    return results[:k]
